databases:
  - name: 65-maika
    databaseName: rails7_sample_staging
    user: 65-maika
    region: singapore

services:
  - type: web
    name: 65-maika
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 65-maika
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false