databases:
  - name: 65-maika_DB
    databaseName: db_65_maika_db
    user: 65-maika
    region: singapore

services:
  - type: web
    name: 65-maika
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db_65_maika_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false